pipeline {
    agent any

    stages {
        stage('SCM') {
            steps {
                echo "Cloning from GitHub..."
                git branch: 'main', url: 'https://github.com/iamsumit24/simple-java-maven-app1.git'
            }
        }

        stage('Deploy') {
            steps {
                echo "Deploying my code"
            }
        }

        stage('Test') {
            steps {
                echo "Testing my final webapp"
            }
        }

        stage('Deploy to Prod') {
            steps {
                echo "Deploying to production"
            }
        }
    }
}
